name: CI Pipeline for Playwright Tests

on:
  push:
    branches:
      - CreatePost1Test
  pull_request:
    branches:
      - CreatePost1Test
  workflow_dispatch:

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: ${{ github.workspace }}/DemoPlaywright/DemoPlaywright/DemoPlaywright.csproj

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore Project
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

    - name: Install Playwright CLI and browsers
      run: |
        dotnet tool install --global Microsoft.Playwright.CLI
        playwright install --with-deps

    - name: Clean
      run: dotnet clean "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }}

    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal

    - name: Publish test results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: "**/TestResults/*.trx"