name: CI Pipeline for Playwright Tests

on:
  push:
    branches:
      - CreatePost1Test  # Chạy trên nhánh CreatePost1Test
  pull_request:
    branches:
      - CreatePost1Test  # Chạy trên nhánh CreatePost1Test
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Cần quyền đọc để checkout code

    steps:
    # Bước 1: Checkout code từ repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Bước 2: Debug cấu trúc thư mục
    - name: Debug directory structure
      run: |
        ls -R
        pwd
        find . -name "DemoPlaywright.sln"
        find . -name "DemoPlaywright.csproj"

    # Bước 3: Thiết lập .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # Bước 4: Cài đặt Playwright dependencies
    - name: Install Playwright dependencies
      run: |
        dotnet restore DemoPlaywright.sln
        dotnet tool install --global Microsoft.Playwright.CLI
        playwright install --with-deps
      working-directory: ${{ github.workspace }}

    # Bước 5: Clean dự án
    - name: Clean project
      run: dotnet clean DemoPlaywright.csproj --configuration Release
      working-directory: ${{ github.workspace }}/DemoPlaywright/DemoPlaywright

    # Bước 6: Build dự án
    - name: Build project
      run: dotnet build DemoPlaywright.csproj --configuration Release
      working-directory: ${{ github.workspace }}/DemoPlaywright/DemoPlaywright

    # Bước 7: Chạy các test
    - name: Run tests
      run: dotnet test DemoPlaywright.csproj --configuration Release --no-build --verbosity normal
      working-directory: ${{ github.workspace }}/DemoPlaywright/DemoPlaywright